### PR TITLE
SSE-2590: Deploy support stacks

### PR DESCRIPTION
**Pull request by CharlesIC**
**Use a nested stack to deploy the support stacks**

The stack can be applied to any account and automatically validates the account and provides correct config.

- Create a new template to deploy all the support stacks
- Add a script to deploy the stack
- Remove old per-account and shared scripts

**Add a script to handle AWS account checking logic**

- Retire and expand on the previous `check-aws-account.sh` script
- Add AWS account config in JSON format
- Add functionality to parse the account config

### CODE REVIEW

**Comment by abdul-gds** [comment]
So we still be deploying **secure pipeline stacks** using dev-platform script 
- sse-frontend-deployer
- sse-cognito-deployer 
- sse-dynamo-db-deployer 
- sse-backend-api-deployer


As nested stack will be generated with **name random id**, It means stack name in secure pipeline ( i.e slack-stack and Vpc-stack  ) can not be hardcoded and It will get changed, on nested stack deployment.

**Comment by CharlesIC** [comment]
> So we still be deploying **secure pipeline stacks** using dev-platform script 
> 
> - sse-frontend-deployer
> 
> - sse-cognito-deployer 
> 
> - sse-dynamo-db-deployer 
> 
> - sse-backend-api-deployer
> 
> 
> 
> 
> 
> As nested stack will be generated with **name random id**, It means stack name in secure pipeline ( i.e slack-stack and Vpc-stack  ) can not be hardcoded and It will get changed, on nested stack deployment.

@abdul-gds for now yes, the pipeline stacks will continue to be deployed using the script, but we will switch to nested stacks for those too once dev platform resolve a few issues.

The names of the VPC and Slack stacks will be exported and imported in the pipelines.

**Review by abdul-gds — APPROVED** [review]
looks good

**Review by rafal-surowiec-co — APPROVED** [review]
looks good

**Pull request merged**
