### PR TITLE
DFA-2244: Macros view update

### PR DESCRIPTION
**Pull request by BorisP-GDS**
**Add base form template and text input macros** 

Add form and textInput macros
Use the form macros in views and base form views on the base form template

Use URL, email, password, security code and mobile phone number inputs as needed

Controllers:
  - Don't handle exceptions when the handling code is the same as the default error handler in `app.ts`
  - Remove unnecessary auth checks in the sign-in flow for some pages
  - Pass values correctly to views - use objects for the form parameters (`values`) and error messages

**Add base form layout for the service-details views** 

Use the service details form layout in some service details form views

---

-  Move layout.njk to layout/base.njk

### CODE REVIEW

**Review by CharlesIC — DISMISSED** [review]

**Review by CharlesIC — APPROVED** [review]

**Review by CharlesIC — DISMISSED** [review]

**Review by HarshVasudev — COMMENTED** [review]
Changes look good. But There are some ES lint related build failures. Are we going to address them?

**Comment by BorisP-GDS** [comment]
@HarshVasudev , These are warnings - (0 errors, 22 warnings) , they will be resolved later. Not an issue for this PR

**Comment by CharlesIC** [comment]
> Changes look good. But There are some ES lint related build failures. Are we going to address them?

Thanks for reviewing @HarshVasudev 
We will address thse `TUV` warnings separately so we can ignore them for this PR

**Review by HarshVasudev — APPROVED** [review]
Approving.

**Pull request merged**
