### PR TITLE
Fixed TxMA event formatting

### PR DESCRIPTION
**Pull request by JamesCarterDI**

### CODE REVIEW

**Review by MartinH-DI — COMMENTED** [review]
You should only need the list disable on the line above the result clause.

**Review by MartinH-DI — APPROVED** [review]
Looks good

**Review by keith-hart — DISMISSED** [review]
refactoring requested

**Review by MartinH-DI — APPROVED** [review]
Changes are ok, build cleanly and I can run up the environment!

**Review by keith-hart — APPROVED** [review]

**Pull request merged**
